#!/usr/bin/env bash

# We want to catch any unexpected failure, and exit immediately
set -e

# Download helper for curl, to be called from the download wrapper script
#
# Call it as:
#   .../curl [-q] OUT_FILE URL
#
# Environment:
#   WGET     : the curl command to call (it named for compatibility)

verbose=
while getopts :q OPT; do
    case "${OPT}" in
    q)  verbose=-\#;;
    \?) printf "unknown option '%s'\n" "${OPTARG}" >&2; exit 1;;
    esac
done
shift $((OPTIND-1))

output="${1}"
url="${2}"

# Caller needs to single-quote its arguments to prevent them from
# being expanded a second time (in case there are spaces in them)
_curl() {
    eval ${WGET} "${@}"
}

_curl ${verbose} -L -o "'${output}'" "'${url}'"
